# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relawan',
            name='count_target',
        ),
        migrations.RemoveField(
            model_name='relawan',
            name='sisa_target',
        ),
    ]
